# Generated by Django 5.0.6 on 2024-06-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='inscription',
            old_name='workload',
            new_name='workload_id',
        ),
        migrations.RenameField(
            model_name='inscriptionlab',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='inscriptionlab',
            old_name='workload',
            new_name='workload_id',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='courseId',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='workloadlab',
            old_name='laboratory',
            new_name='laboratory_id',
        ),
        migrations.RenameField(
            model_name='workloadlab',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.AddField(
            model_name='inscription',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscriptionlab',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
