# Generated by Django 5.0.6 on 2024-06-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_rename_student_inscription_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisites_%(class)s_set', to='matriculas.course'),
        ),
    ]
