# Generated by Django 5.0.6 on 2024-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0004_inscription_course_status_inscription_nro_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionlab',
            name='course_status',
            field=models.IntegerField(choices=[(1, 'Matriculado'), (2, 'Aprobado'), (3, 'Reprobado'), (4, 'Abandonado')], default=1),
        ),
        migrations.AddField(
            model_name='inscriptionlab',
            name='nro_matricula',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='course_status',
            field=models.IntegerField(choices=[(1, 'Matriculado'), (2, 'Aprobado'), (3, 'Reprobado'), (4, 'Abandonado')], default=1),
        ),
    ]
